### ISSUE TITLE
Bug: src refspec docs/update-from-wiki does not match any

### ISSUE THREAD

**Issue by TGTGamer** [newrelic/wiki-sync-action#1]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Heya guys, Encountering an issue when changing a markdown file in the repo.wiki.git through the online editor. Not entirely sure what the error is due to the lack of console output information, but here is everything you should need. 

```yml
name: Documentation

on:
  push:
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum:

jobs:
  # syncs from the github inbuilt wiki
  job-sync-wiki-to-docs:
    name: Sync from wiki
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@master
        with:
          source: wiki
          destination: docs
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'docs/update-from-wiki'
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'master'
          destination_branch: 'docs/update-from-wiki'
          pr_title: "docs: updating docs from wiki"
          pr_body: ":crown: *An automated PR*"
          pr_label: "skip-changelog"
```

## Expected Behaviour

Expected to checkout `repo.wiki.git`, and sync them with `master` document (`docs`) folder. Then push to branch `docs/update-from-wiki` 

## Relevant Logs / Console output

```cmd
[master 1dcc623] chore(docs): Sync wiki to docs [skip-cd]
 3 files changed, 87 insertions(+)
 create mode 100644 docs/Home.md
 create mode 100644 docs/_Footer.md
error: src refspec docs/update-from-wiki does not match any
 create mode 100644 docs/_Sidebar.md
error: failed to push some refs to 'https://github.com/Videndum/Smartcloud'
```
