### ISSUE TITLE
Bug: access denied or repository not exported error stops action from working

### ISSUE THREAD

**Issue by lwcooper** [newrelic/wiki-sync-action#2]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

- When running either the docs-to-wiki or wiki-to-sync job, there is an error printed to the action logs stating `fatal: remote error: access denied or repository not exported: [Stuff that looks like /a/b/cc/dd/ee/8359252938].wiki.git`

## Steps to Reproduce

Used the following actions config file:

```
name: Docs/Wiki Sync

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum:

env:
  GIT_AUTHOR_EMAIL: opensource+bot@newrelic.com
  GIT_AUTHOR_NAME: nr-opensource-bot

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@master
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.WIKI_SYNC_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}

  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WIKI_SYNC_TOKEN }} # allows us to push back to repo
          ref: main
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@master
        with:
          source: wiki
          destination: docs
          token: ${{ secrets.WIKI_SYNC_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: main
```

I also tried with the `GITHUB_TOKEN` passed through actions instead of making a secret in the repository

I also tried making the repository public to see if that helped

I then edited a document in the `docs` folder and observed the action being run

## Expected Behaviour

The action should have synced the docs to the wiki

## Relevant Logs / Console output

```
fatal: remote error: access denied or repository not exported: /*/**/**/**/**/*********/*********.wiki.git
sending incremental file list
./
**.md
**.md
**.md

sent 402 bytes  received 76 bytes  956.00 bytes/sec
total size is 142  speedup is 0.30
[master (root-commit) 9e652e3] chore(docs): Sync docs to wiki [skip-cd]
 3 files changed, 21 insertions(+)
 create mode 100644 **.md
 create mode 100644 **.md
 create mode 100644 **.md
fatal: could not read Password for 'https://***@github.com': No such device or address
```

## Your Environment

As per the action

## Additional context

[TIP]:  # ( Add any other context about the problem here. )
