### ISSUE TITLE
Workflow succeeds on fatal git error caused by an empty gitAuthorEmail.

### ISSUE THREAD

**Issue by jifalops** [newrelic/wiki-sync-action#7]
## Description

I have a workflow setup where I tried to use `gitAuthorEmail: ${{ github.event.sender.email }}`  for wiki -> docs sync. That value is apparently blank and git had a fatal error (`fatal: empty ident name (for <@users.noreply.github.com>) not allowed`) but the workflow was regarded as successful in github.

## Steps to Reproduce

<details><summary>Working workflow.yml with comment about where the error occurs (near the end) </summary>

```yml
name: Wiki Sync

on:
  push:
    branches:
      - master
    paths:
      - "doc/wiki/**"
  # Wiki events generated by github.
  # Only created and updated are sent, if a page is deleted from the wiki's web UI,
  # it will not be synced. Deletes should happen on the local file for it to be
  # synced to the wiki repo.
  gollum:

permissions: write-all

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum' && github.event.commits[0].author.email != 'wikisyncbot@users.noreply.github.com'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@8fb7a9efe4e975bdb2977107fbed96fa0433db52
        with:
          source: doc/wiki
          destination: wiki
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          gitAuthorName: ${{ github.event.pusher.name }}
          gitAuthorEmail: ${{ github.event.pusher.email }}
          commitMessage: ${{ github.event.head_commit.message }}


  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ref: master
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@8fb7a9efe4e975bdb2977107fbed96fa0433db52
        with:
          source: wiki
          destination: doc/wiki
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          gitAuthorName: WikiSyncBot
          # 
          # 
          #  Fails when using the EMPTY value:
          #  github.event.sender.email
          #          
          gitAuthorEmail: wikisyncbot@users.noreply.github.com
          commitMessage: |
            Wiki-sync: ${{ join(github.event.pages.*.page_name) }}

            ${{ toJson(github.event.pages) }}
          branch: master
```
</details>

## Expected Behaviour

If git fails to commit, the sync has failed and therefore the workflow should fail.
